# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='Nom',
        ),
        migrations.AlterField(
            model_name='carte',
            name='valueB',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valueD',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valueG',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='carte',
            name='valueH',
            field=models.BigIntegerField(),
        ),
    ]
