# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_auto_20180108_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='Nom',
            field=models.CharField(default='mescouilles', max_length=80),
            preserve_default=False,
        ),
    ]
