# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_carte_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carte',
            old_name='valueB',
            new_name='bas',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='valueD',
            new_name='droite',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='valueG',
            new_name='gauche',
        ),
        migrations.RenameField(
            model_name='carte',
            old_name='valueH',
            new_name='haut',
        ),
    ]
